apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: student-management
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - devops
  selector:
    matchLabels:
      app: spring-app
  endpoints:
    - port: http
      path: /student/actuator/prometheus
      interval: 15s
